title: devnull
email: ewinningham@gmail.com
description: >-
  Within this space are the ramblings of a mad devops engineer, maker, husband, and father.
baseurl: ""
url: "https://winningham.me"
github_username:  policyoftruth
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
