# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "nulldiv-web-tf"
    encrypt      = true
    key          = "route53/state/tfstate.state"
    region       = "us-east-1"
    use_lockfile = true
  }
}
