name: terragrunt

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TERRAGRUNT_VERSION: 0.31.7
      TERRAGRUNT_SHA256SUM: c1d863e8fa1c994a79338b28ec72dd97a97cff5d485691832c7304b43886a929 # pragma: allowlist secret
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2
      - name: download terragrunt
        run: |
          curl -L --output ./terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 && \
          echo "${TERRAGRUNT_SHA256SUM}  ./terragrunt" > terragrunt-${TERRAGRUNT_VERSION}_SHA256SUMS && \
          sha256sum -c terragrunt-${TERRAGRUNT_VERSION}_SHA256SUMS && \
          chmod +x ./terragrunt && \
          sudo mv ./terragrunt /usr/bin/terragrunt
      - name: terragrunt init/plan
        run: |
          terragrunt init
          terragrunt plan
